syntax = "proto3";

package grpcgo;

option go_package = "routes/proto;proto";

import "google/protobuf/struct.proto";

service Base {
  rpc Get(DynamicRequest) returns (BaseResponse);
  rpc Administrate(DynamicRequest) returns (BaseResponse);
}

message Server {
  string name = 1;
  string version = 2;
  string message = 3;
}

message PageMetadata {
  int32 total = 1;
  int32 page = 2;
  int32 pageSize = 3;
  Server server = 4;
}

message DynamicRequest {
  int32 method = 1;
  string collection = 2;
  map<string, string> filters = 3; // Puedes dejar esto si solo necesitas filtros simples
  Config config = 4;
}

message Config {
  int64 page = 1;
  int64 pageSize = 2;
}

message BaseResponse {
  int32 status = 1;
  string message = 2;
  repeated Data data = 3;
  optional PageMetadata meta = 4;
}

message Data {
  google.protobuf.Struct data = 1; // Aquí se permite estructura anidada y compleja
 }
