syntax = "proto3";

package grpcgo;

option go_package = "./proto;proto";

service Base {
  rpc Get(DynamicRequest) returns (BaseResponse);
  rpc Administrate(DynamicRequest) returns (BaseResponse);
}

message Server {
  string name = 1;
  string version = 2;
  string message = 3;
}

message DynamicRequest {
  int32 method = 1;
  string collection = 2;
  map<string, string> filters = 3; // Permite datos flexibles en JSON
}


message BaseResponse {
  int32 status = 1;
  string message = 2;
  repeated Data data = 3; // Respuesta flexible en JSON
  Server server = 4;
}

message Data {
  map<string, string> data = 1;
}
